### ISSUE TITLE
How do I run a single test only in Cavy?

### ISSUE THREAD

**Issue by TaylorMichaelHall** [pixielabs/cavy#174] opened 2020-05-08 17:07 UTC
We have many tests but sometimes we only want to troubleshoot a single test that has failed, and it's time consuming to run the entire test suite to debug a single test.

Thanks!

**Comment by AbigailMcP** [comment] 2020-05-12 09:00
Hi there! I have some good news and some bad news for you...

Bad news: at the moment, there's no API to run just one test - you'd have to comment out other tests, or if the tests you want to run are exported from just one file, pass that one spec function into your `Tester` component.

Good news: we're in the process of updating the roadmap for Cavy (soon to be made public) and running a subset of tests is on there!

I feel this a duplicate of https://github.com/pixielabs/cavy/issues/164, so will close this issue and continue the discussion there.

Thanks for your interest in Cavy :)

**Closed** 2020-05-12 09:00 UTC
